# Generated by Django 2.1 on 2018-08-15 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of Image', max_length=100)),
                ('source', models.CharField(help_text='URL of the image location (S3... etc.)', max_length=200)),
                ('description', models.TextField(help_text='Description of the image. Used for alt text if no alt text is provided.')),
                ('alt_text', models.TextField(help_text='Alt text')),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
                ('publish_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
