# Generated by Django 2.1 on 2018-08-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='source',
            new_name='source_standard',
        ),
        migrations.AddField(
            model_name='image',
            name='source_large',
            field=models.CharField(default='', help_text='URL of the image location (S3... etc.)', max_length=200),
        ),
        migrations.AddField(
            model_name='image',
            name='source_small',
            field=models.CharField(default='', help_text='URL of the image location (S3... etc.)', max_length=200),
        ),
    ]
