# Generated by Django 2.1 on 2018-08-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20180815_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='source_large',
            field=models.ImageField(help_text='URL of the image location (S3... etc.)', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='source_small',
            field=models.ImageField(help_text='URL of the image location (S3... etc.)', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='source_standard',
            field=models.ImageField(help_text='URL of the image location (S3... etc.)', upload_to='images/'),
        ),
    ]
