# Generated by Django 2.1 on 2018-08-28 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0008_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-publish_date']},
        ),
    ]
